-- =========================
-- TABLES
-- =========================

CREATE TABLE public.users (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              created_at TIMESTAMP,
                              email VARCHAR(255) UNIQUE NOT NULL,
                              currency VARCHAR(10) DEFAULT 'NGN' CHECK (currency IN ('NGN', 'GHS', 'USD', 'EUR', 'GBP')),
                              full_name VARCHAR(255) NOT NULL,
                              password_hash VARCHAR(255) NOT NULL,
                              updated_at TIMESTAMP,
                              username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE public.categories (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   color VARCHAR(7),
                                   created_at TIMESTAMP,
                                   icon VARCHAR(50),
                                   is_default BOOLEAN,
                                   name VARCHAR(100) NOT NULL,
                                   user_id BIGINT
);

CREATE TABLE public.recurring_expenses (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           amount NUMERIC(15,2) NOT NULL,
                                           created_at TIMESTAMP,
                                           description VARCHAR(500) NOT NULL,
                                           end_date DATE,
                                           frequency VARCHAR(20) NOT NULL,
                                           is_active BOOLEAN,
                                           next_execution_date DATE NOT NULL,
                                           payment_method VARCHAR(50) NOT NULL,
                                           start_date DATE NOT NULL,
                                           updated_at TIMESTAMP,
                                           category_id BIGINT NOT NULL,
                                           user_id BIGINT NOT NULL
);

CREATE TABLE public.budgets (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                created_at TIMESTAMP,
                                fixed_expenses NUMERIC(15,2),
                                income NUMERIC(15,2) NOT NULL,
                                month_year VARCHAR(7) NOT NULL,
                                notes TEXT,
                                savings_allocation NUMERIC(15,2),
                                updated_at TIMESTAMP,
                                user_id BIGINT NOT NULL
);

CREATE TABLE public.expenses (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 amount NUMERIC(15,2) NOT NULL,
                                 created_at TIMESTAMP,
                                 description VARCHAR(500) NOT NULL,
                                 expense_date TIMESTAMP NOT NULL,
                                 is_recurring BOOLEAN,
                                 note TEXT,
                                 payment_method VARCHAR(50) NOT NULL,
                                 updated_at TIMESTAMP,
                                 category_id BIGINT NOT NULL,
                                 recurring_id BIGINT,
                                 user_id BIGINT NOT NULL
);

-- =========================
-- FOREIGN KEYS
-- =========================

ALTER TABLE public.categories
    ADD FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE public.recurring_expenses
    ADD FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE public.recurring_expenses
    ADD FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE public.budgets
    ADD FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE public.expenses
    ADD FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE public.expenses
    ADD FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE public.expenses
    ADD FOREIGN KEY (recurring_id) REFERENCES public.recurring_expenses(id);

-- =========================
-- SEED DATA (categories)
-- =========================

INSERT INTO public.categories (id, color, created_at, icon, is_default, name, user_id) VALUES
                                                                                           (1, '#FF6B6B', NULL, '🍽️', true, 'Food & Dining', NULL),
                                                                                           (2, '#4ECDC4', NULL, '🚗', true, 'Transportation', NULL),
                                                                                           (3, '#FFE66D', NULL, '🛍️', true, 'Shopping', NULL),
                                                                                           (4, '#95E1D3', NULL, '💡', true, 'Bills & Utilities', NULL),
                                                                                           (5, '#F38181', NULL, '🎬', true, 'Entertainment', NULL),
                                                                                           (6, '#AA96DA', NULL, '💪', true, 'Health & Fitness', NULL),
                                                                                           (7, '#FCBAD3', NULL, '📚', true, 'Education', NULL),
                                                                                           (8, '#A8E6CF', NULL, '🛒', true, 'Groceries', NULL),
                                                                                           (9, '#FFB4A2', NULL, '💄', true, 'Personal Care', NULL),
                                                                                           (10, '#6C5CE7', NULL, '✈️', true, 'Travel', NULL),
                                                                                           (11, '#FDA7DF', NULL, '🎁', true, 'Gifts & Donations', NULL),
                                                                                           (12, '#B2BABB', NULL, '📌', true, 'Miscellaneous', NULL);

-- =========================
-- FIX SEQUENCE
-- =========================

SELECT setval('public.categories_id_seq', 12, true);